RecruitmentAgency/Models/Candidate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;

#nullable disable

namespace RecruitmentAgency.Models
{
    public partial class Candidate
    {
        public Candidate()
        {
            Applications = new HashSet<Application>();
        }

        public int CandidateId { get; set; }
        [Display(Name = "First name", Prompt = "First name")]
        [Required(ErrorMessage = "First name is required")]
        [RegularExpression("^[A-Z][a-z]+$")]
        public string FirstName { get; set; }
        [Display(Name = "Last name", Prompt = "Last name")]
        [Required(ErrorMessage = "Last name is required")]
        [RegularExpression("^[A-Z][a-z]+$")]
        public string LastName { get; set; }
        [Display(Name = "Department", Prompt = "Department")]
        [Required(ErrorMessage = "Department is required")]
        public int DepartmentId { get; set; }
        [Display(Name = "Email", Prompt = "Email")]
        [EmailAddress(ErrorMessage = "Invalid format of email")]
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "--")]
        public string Email { get; set; }
        [Display(Name = "Phone number", Prompt = "Phone number")]
        [Phone(ErrorMessage = "Invalid format of phone number")]
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "--")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Resume file")]
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "--")]
        public string ResumeUrl { get; set; }

        [Display(Name = "Rating", Prompt = "Rating")]
        [Range(0, 5, ErrorMessage = "Rating must be in range [0; 5]")]
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "--")]
        public decimal? Rating { get; set; }

        [NotMapped]
        [Display(Name = "Resume")]
        [DataType(DataType.Upload)]
        public IFormFile Resume { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }

        [Display(Name="Department")]
        public virtual Department Department { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
    }
}

RecruitmentAgency/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecruitmentAgency.Data;
using RecruitmentAgency.Models;
using RecruitmentAgency.ViewModels;

namespace RecruitmentAgency.Controllers
{
    public class CandidatesController : Controller
    {
        private readonly RecruiterAgencyContext _context;
        private readonly IWebHostEnvironment _webHost;

        public CandidatesController(RecruiterAgencyContext context, IWebHostEnvironment webHost)
        {
            _context = context;
            _webHost = webHost;
        }

        // GET: Candidates
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 10, string searchQuery = null)
        {
            IQueryable<Candidate> recruiterAgencyContext = _context.Candidates
                .Include(c => c.Department)
                .ThenInclude(x => x.City);
            if (!string.IsNullOrWhiteSpace(searchQuery))
            {
                recruiterAgencyContext = recruiterAgencyContext.Where(x =>
                    x.FirstName.Contains(searchQuery)
                    || x.LastName.Contains(searchQuery)
                    || x.Department.City.Name.Contains(searchQuery)
                    || x.Department.Address.Contains(searchQuery)
                    || x.PhoneNumber.Contains(searchQuery)
                    || x.Email.Contains(searchQuery));
            }

            var paginated = await Paginated<Candidate>.PaginateAsync(recruiterAgencyContext, pageIndex, pageSize);
            paginated.SearchQuery = searchQuery;

            return View(await recruiterAgencyContext.ToListAsync());
        }

        // GET: Candidates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidate = await _context.Candidates
                .Include(c => c.Department)
                .ThenInclude(x => x.City)
                .FirstOrDefaultAsync(m => m.CandidateId == id);
            if (candidate == null)
            {
                return NotFound();
            }

            return PartialView("_DetailsDialog", candidate);
        }

        // GET: Candidates/Create
        public async Task<IActionResult> Create()
        {
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            return View();
        }

        // POST: Candidates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                if (candidate.Resume != null)
                {
                    var filePath = "Resumes\\" + candidate.Resume.FileName;
                    await using (var stream =
                        new FileStream(Path.Combine(_webHost.WebRootPath, filePath), FileMode.Create))
                    {
                        await candidate.Resume.CopyToAsync(stream);
                    }

                    candidate.ResumeUrl = filePath;
                }

                candidate.CreateDate = DateTime.Now;
                _context.Add(candidate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            return View(candidate);
        }

        // GET: Candidates/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidate = await _context.Candidates.FindAsync(id);
            if (candidate == null)
            {
                return NotFound();
            }

            try
            {
                await using var stream =
                    new FileStream(Path.Combine(_webHost.ApplicationName, candidate.ResumeUrl), FileMode.Open);
                candidate.Resume = new FormFile(stream, stream.Position, stream.Length,
                    Path.GetFileNameWithoutExtension(stream.Name), Path.GetFileName(stream.Name));
            }
            catch (Exception)
            {
                // ignore
            }

            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            return View(candidate);
        }

        // POST: Candidates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CandidateId,FirstName,LastName,Rating,DepartmentId,Email,PhoneNumber,Resume,CreateDate")] Candidate candidate)
        {
            if (id != candidate.CandidateId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (candidate.Resume != null)
                    {
                        var filePath = "Resumes\\" + candidate.Resume.FileName;
                        await using (var stream =
                            new FileStream(Path.Combine(_webHost.WebRootPath, filePath), FileMode.OpenOrCreate))
                        {
                            await candidate.Resume.CopyToAsync(stream);
                        }

                        candidate.ResumeUrl = filePath;
                    }

                    candidate.UpdateDate = DateTime.Now;
                    _context.Update(candidate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CandidateExists(candidate.CandidateId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            return View(candidate);
        }

        // GET: Candidates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidate = await _context.Candidates
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.CandidateId == id);
            if (candidate == null)
            {
                return NotFound();
            }

            return View(candidate);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var candidate = await _context.Candidates.FindAsync(id);
            _context.Candidates.Remove(candidate);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CandidateExists(int id)
        {
            return _context.Candidates.Any(e => e.CandidateId == id);
        }
    }
}

RecruitmentAgency/Views/Candidates/Create.cshtml
@model RecruitmentAgency.Models.Candidate

@{
    ViewData["Title"] = "Create candidate";
}

<div class="container-fluid">
    <section>
        <div id="multple-step-form-n" class="container overflow-hidden" style="margin-top: 0px;margin-bottom: 10px;padding-bottom: 50px;padding-top: 57px;">

            <div id="multistep-start-row" class="row">
                <div id="multistep-start-column" class="col-12 col-lg-8 m-auto">
                    <form id="main-form" class="multisteps-form__form" asp-action="Create" enctype="multipart/form-data">

                        <div id="single-form-next" class="multisteps-form__panel p-4 shadow rounded bg-white js-active" data-animation="scaleIn">
                            <h3 class="text-center multisteps-form__title">Create candidate</h3>
                            <div id="form-content" class="multisteps-form__content">
                                
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div id="input-grp-double" class="form-row mt-4">
                                    <div class="col-12 col-sm-6">
                                        <label asp-for="FirstName"></label>
                                        <input asp-for="FirstName" class="form-control multisteps-form__input" type="text">

                                        <span asp-validation-for="FirstName" class="text-danger"></span>
                                    </div>
                                    <div class="col-12 col-sm-6 mt-4 mt-sm-0">
                                        <label asp-for="LastName"></label>
                                        <input asp-for="LastName" class="form-control multisteps-form__input" type="text">

                                        <span asp-validation-for="LastName" class="text-danger"></span>
                                    </div>
                                </div>

                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="DepartmentId"></label>
                                        <select asp-for="DepartmentId" class="form-control custom-select multisteps-form__input" asp-items="ViewBag.DepartmentId"></select>
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>


                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="Email"></label>
                                        <input asp-for="Email" class="form-control multisteps-form__input" type="email">
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>


                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="PhoneNumber"></label>
                                        <input asp-for="PhoneNumber" class="form-control multisteps-form__input" type="text">
                                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                    </div>


                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="ResumeUrl"></label>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" asp-for="Resume">
                                            <label class="custom-file-label" asp-for="Resume">Choose file...</label>

                                        </div><span asp-validation-for="Resume" class="text-danger"></span>
                                    </div>


                                </div>
                                <div class="button-row d-flex mt-4"><button class="btn btn btn-secondary " type="button" onclick="history.back()" title="Back">Back</button><button class="btn btn btn-primary ml-auto " type="submit" title="Create">Create</button></div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RecruitmentAgency/Views/Candidates/Delete.cshtml
@model RecruitmentAgency.Models.Candidate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Candidate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ResumeUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResumeUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.Address)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CandidateId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RecruitmentAgency/Views/Candidates/Details.cshtml
@model RecruitmentAgency.Models.Candidate

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Candidate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ResumeUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResumeUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CandidateId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RecruitmentAgency/Views/Candidates/Edit.cshtml
@model RecruitmentAgency.Models.Candidate

@{
    ViewData["Title"] = $"Edit {Model.FirstName} {Model.LastName}";
}

<div class="container-fluid">
    <section>
        <div id="multple-step-form-n" class="container overflow-hidden" style="margin-top: 0px;margin-bottom: 10px;padding-bottom: 50px;padding-top: 57px;">

            <div id="multistep-start-row" class="row">
                <div id="multistep-start-column" class="col-12 col-lg-8 m-auto">
                    <form id="main-form" class="multisteps-form__form" asp-action="Edit" enctype="multipart/form-data">
                        <input type="hidden" asp-for="CandidateId"/>
                        <input type="hidden" asp-for="CreateDate"/>
                        <div id="single-form-next" class="multisteps-form__panel p-4 shadow rounded bg-white js-active" data-animation="scaleIn">
                            <h3 class="text-center multisteps-form__title">Edit candidate</h3>
                            <div id="form-content" class="multisteps-form__content">

                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div id="input-grp-double" class="form-row mt-4">
                                    <div class="col-12 col-sm-6">
                                        <label asp-for="FirstName"></label>
                                        <input asp-for="FirstName" class="form-control multisteps-form__input" type="text">

                                        <span asp-validation-for="FirstName" class="text-danger"></span>
                                    </div>
                                    <div class="col-12 col-sm-6 mt-4 mt-sm-0">
                                        <label asp-for="LastName"></label>
                                        <input asp-for="LastName" class="form-control multisteps-form__input" type="text">

                                        <span asp-validation-for="LastName" class="text-danger"></span>
                                    </div>
                                </div>

                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="DepartmentId"></label>
                                        <select asp-for="DepartmentId" class="form-control custom-select multisteps-form__input" asp-items="ViewBag.DepartmentId"></select>
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>


                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="Email"></label>
                                        <input asp-for="Email" class="form-control multisteps-form__input" type="email">
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>


                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="PhoneNumber"></label>
                                        <input asp-for="PhoneNumber" class="form-control multisteps-form__input" type="text">
                                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                    </div>


                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="ResumeUrl"></label>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" asp-for="Resume">
                                            <label class="custom-file-label" asp-for="Resume">Choose file...</label>

                                        </div><span asp-validation-for="Resume" class="text-danger"></span>
                                    </div>


                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="Rating"></label>
                                        <input asp-for="Rating" class="form-control multisteps-form__input" type="number">
                                        <span asp-validation-for="Rating" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="button-row d-flex mt-4"><button class="btn btn btn-secondary " type="button" onclick="history.back()" title="Back">Back</button><button class="btn btn btn-primary ml-auto " type="submit" title="Save">Save</button></div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RecruitmentAgency/Views/Candidates/_DetailsDialog.cshtml
@model RecruitmentAgency.Models.Candidate

<div class="modal fade" id="candidateDetails" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Candidate profile</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <dl class="row">
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Department.City)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Department.City.Name)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Department.Address)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Department.Address)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.ResumeUrl)
                    </dt>
                    <dd class="col-sm-8">
                        @if (string.IsNullOrWhiteSpace(@Model.ResumeUrl))
                        {
                            <span>--</span>
                        }
                        else
                        {
                            <a href="@Html.DisplayFor(model=> model.ResumeUrl)" target="_blank">Download</a>
                        }
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Rating)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Rating)
                    </dd>
                </dl>
            </div>
            <div class="modal-footer">
                <a class="btn btn-outline-primary" asp-controller="Candidates" asp-action="Edit" asp-route-id="@Model.CandidateId">Edit</a>
                <button class="btn btn-light" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>