RecruitmentAgency/Models/Vacancy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace RecruitmentAgency.Models
{
    public partial class Vacancy
    {
        public Vacancy()
        {
            Applications = new HashSet<Application>();
            Payments = new HashSet<Payment>();
        }

        public int VacancyId { get; set; }
        [Display(Name="Job title")]
        public int JobTitleId { get; set; }

        [Display(Name = "Requirements")]
        [MaxLength(4000)]
        public string Requirements { get; set; }
        [Display(Name = "Positions count", Prompt = "Positions count")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Positions count cannot be negative")]
        public int PositionsCount { get; set; }
        [Display(Name = "Start date")]
        public DateTime StartDate { get; set; }
        [Display(Name = "End date")]
        public DateTime? EndDate { get; set; }
        [Display(Name = "Customer")]
        public int CustomerId { get; set; }
        [Display(Name = "Tariff")]
        public int TariffId { get; set; }
        [Display(Name = "Recruiter")]
        public int RecruiterId { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        [Display(Name = "Company office")]
        public int CompanyOfficeId { get; set; }

        [Display(Name = "Company office")]
        public virtual CompanyOffice CompanyOffice { get; set; }

        [Display(Name = "Customer")]
        public virtual Customer Customer { get; set; }
        [Display(Name = "Job title")]
        public virtual JobTitle JobTitle { get; set; }
        [Display(Name = "Recruiter")]
        public virtual Employee Recruiter { get; set; }
        [Display(Name = "Tariff")]
        public virtual Tariff Tariff { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}

RecruitmentAgency/Controllers/VacanciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Razor.Language.CodeGeneration;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using RecruitmentAgency.Data;
using RecruitmentAgency.Models;
using RecruitmentAgency.ViewModels;

namespace RecruitmentAgency.Controllers
{
    public class VacanciesController : Controller
    {
        private readonly RecruiterAgencyContext _context;

        public VacanciesController(RecruiterAgencyContext context)
        {
            _context = context;
        }

        // GET: Vacancies
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 10, string searchQuery = null)
        {
            IQueryable<Vacancy> recruiterAgencyContext = _context.Vacancies
                .Include(v => v.CompanyOffice)
                .ThenInclude(x => x.Company)
                .Include(x => x.CompanyOffice.City)
                .Include(v => v.Customer)
                .Include(v => v.JobTitle)
                .ThenInclude(x => x.JobCategory)
                .Include(v => v.Recruiter)
                .Include(x => x.Applications)
                .Include(x => x.Payments)
                .Include(x => x.Tariff)
                .Where(x => x.RecruiterId == int.Parse(HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier)));
            //if (!string.IsNullOrWhiteSpace(searchQuery))
            //{
            //    recruiterAgencyContext = recruiterAgencyContext.Where(x =>
            //        x.CompanyOffice.Company.Name.Contains(searchQuery)
            //        || x.CompanyOffice.City.Name.Contains(searchQuery)
            //        || x.CompanyOffice.Address.Contains(searchQuery)
            //        || x.Customer.FirstName.Contains(searchQuery)
            //        || x.Customer.LastName.Contains(searchQuery)
            //        || x.JobTitle.Name.Contains(searchQuery));
            //}

            //var paginated = await Paginated<Vacancy>.PaginateAsync(recruiterAgencyContext, pageIndex, pageSize);
            //paginated.SearchQuery = searchQuery;

            return View(await recruiterAgencyContext.ToListAsync());
        }

        // GET: Vacancies/1/Applications
        [Route("Vacancies/{vacancyId}/Applications")]
        public async Task<IActionResult> Applications(int vacancyId, int pageIndex = 1, int pageSize = 10, string searchQuery = null)
        {
            var vacancy = await _context.Vacancies
                .Include(x => x.CompanyOffice)
                .ThenInclude(x => x.Company)
                .Include(x => x.CompanyOffice.City)
                .Include(x => x.Customer)
                .Include(x => x.JobTitle)
                .ThenInclude(x => x.JobCategory)
                .FirstOrDefaultAsync(x =>
                    x.VacancyId == vacancyId &&
                    x.RecruiterId == int.Parse(HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier)));
            if (vacancy == null)
            {
                return Forbid();
            }

            IQueryable<Application> recruiterAgencyContext = _context.Applications
                .Include(x => x.Candidate)
                .ThenInclude(x => x.Department)
                .ThenInclude(x => x.City)
                .Include(x => x.ApplicationStatus)
                .Include(x => x.Vacancy)
                .Where(x => x.VacancyId == vacancyId);
            //if (!string.IsNullOrWhiteSpace(searchQuery))
            //{
            //    recruiterAgencyContext = recruiterAgencyContext.Where(x =>
            //        x.Candidate.FirstName.Contains(searchQuery)
            //        || x.Candidate.LastName.Contains(searchQuery));
            //}

            //var paginated = await Paginated<Application>.PaginateAsync(recruiterAgencyContext, pageIndex, pageSize);
            //paginated.SearchQuery = searchQuery;
            var response = new VacancyApplicationsResponse
            {
                VacancyId = vacancyId,
                VacancyCustomer = $"{vacancy.Customer.FirstName} {vacancy.Customer.LastName}",
                VacancyJobTitle = $"{vacancy.JobTitle.Name}",
                VacancyCompany = vacancy.CompanyOffice.Company.Name,
                VacancyCompanyOffice = $"{vacancy.CompanyOffice.City.Name}, {vacancy.CompanyOffice.Address}",
                Applications = await recruiterAgencyContext.ToListAsync(),
                VacancyClosed = vacancy.EndDate.HasValue
            };

            return View("Applications/Index", response);
        }

        // GET: Vacancies/Details/5
        public async Task<IActionResult> Details(int? id, bool? showViewApplications)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vacancy = await _context.Vacancies
                .Include(v => v.CompanyOffice)
                .ThenInclude(x => x.Company)
                .Include(x => x.CompanyOffice.City)
                .Include(v => v.Customer)
                .Include(v => v.JobTitle)
                .ThenInclude(x => x.JobCategory)
                .Include(v => v.Recruiter)
                .Include(x => x.Applications)
                .Include(x => x.Tariff)
                .Include(x => x.Payments)
                .FirstOrDefaultAsync(m => m.VacancyId == id);
            if (vacancy == null)
            {
                return NotFound();
            }

            ViewData["ShowViewApplications"] = showViewApplications ?? true;
            return PartialView("_DetailsDialog", vacancy);
        }

        // GET: Vacancies/Create
        public async Task<IActionResult> Create()
        {
            ViewData["CompanyOffice"] = await _context.CompanyOffices
                .Include(x => x.City)
                .Select(x => new { x.CompanyId, Value = x.CompanyOfficeId, Text = $"{x.City.Name}, {x.Address}"})
                .ToListAsync();
            ViewData["Customer"] = await _context.Customers
                .Select(x => new { x.CompanyId, Value = x.CustomerId, Text = $"{x.FirstName} {x.LastName}"})
                .ToListAsync();
            ViewData["JobTitle"] = await _context.JobTitles
                .Select(x => new {x.JobCategoryId, Value = x.JobTitleId, Text = x.Name})
                .ToListAsync();
            ViewData["TariffId"] = new SelectList(_context.Tariffs.Where(x => x.BeginDate <= DateTime.Now && x.EndDate >= DateTime.Now), "TariffId", "Name");
            ViewData["Tariff"] = await _context.Tariffs
                .Where(x => x.BeginDate <= DateTime.Now && x.EndDate >= DateTime.Now)
                .Select(x => new {Value = x.TariffId, Cost = x.PriceForCandidate})
                .ToListAsync();
            ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Name");
            ViewData["JobCategoryId"] = new SelectList(_context.JobCategories, "JobCategoryId", "Name");
            return View();
        }

        // POST: Vacancies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("JobTitleId,Requirements,PositionsCount,CustomerId,TariffId,CompanyOfficeId")] Vacancy vacancy)
        {
            if (ModelState.IsValid)
            {
                vacancy.RecruiterId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                vacancy.StartDate = vacancy.CreateDate = DateTime.Now;
                _context.Add(vacancy);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyOffice"] = await _context.CompanyOffices
                .Include(x => x.City)
                .Select(x => new { x.CompanyId, Value = x.CompanyOfficeId, Text = $"{x.City.Name}, {x.Address}" })
                .ToListAsync();
            ViewData["Customer"] = await _context.Customers
                .Select(x => new { x.CompanyId, Value = x.CustomerId, Text = $"{x.FirstName} {x.LastName}" })
                .ToListAsync();
            ViewData["JobTitle"] = await _context.JobTitles
                .Select(x => new { x.JobCategoryId, Value = x.JobTitleId, Text = x.Name })
                .ToListAsync();
            ViewData["TariffId"] = new SelectList(_context.Tariffs.Where(x => x.BeginDate <= DateTime.Now && x.EndDate >= DateTime.Now), "TariffId", "Name");
            ViewData["Tariff"] = await _context.Tariffs
                .Where(x => x.BeginDate <= DateTime.Now && x.EndDate >= DateTime.Now)
                .Select(x => new { Value = x.TariffId, Cost = x.PriceForCandidate })
                .ToListAsync();
            ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Name");
            ViewData["JobCategoryId"] = new SelectList(_context.JobCategories, "JobCategoryId", "Name");
            return View(vacancy);
        }

        // GET: Vacancies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vacancy = await _context.Vacancies
                .Include(x => x.Applications)
                .ThenInclude(x => x.ApplicationStatus)
                .Include(x => x.CompanyOffice)
                .Include(x => x.JobTitle)
                .FirstOrDefaultAsync(x => x.VacancyId == id);
            if (vacancy == null)
            {
                return NotFound();
            }
            ViewData["CompanyOfficeId"] = await _context.CompanyOffices
                .Include(x => x.City)

RecruitmentAgency/Views/Vacancies/Create.cshtml
@using System.Globalization
@using Newtonsoft.Json
@model RecruitmentAgency.Models.Vacancy

@{
    ViewData["Title"] = "Create vacancy";
}

<div class="container-fluid">
    <section>
        <div id="multple-step-form-n" class="container overflow-hidden" style="margin-top: 0px;margin-bottom: 10px;padding-bottom: 50px;padding-top: 57px;">

            <div id="multistep-start-row" class="row">
                <div id="multistep-start-column" class="col-12 col-lg-8 m-auto">
                    <form id="main-form" class="multisteps-form__form" asp-action="Create">
                        <div id="single-form-next" class=" p-4 shadow rounded bg-white js-active" data-animation="scaleIn">
                            <h3 class="text-center multisteps-form__title">Create vacancy</h3>
                            <div id="form-content" class="multisteps-form__content">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-row mt-4">
                                    <div class="col-12 col-sm-6">
                                        <label asp-for="CompanyOffice.CompanyId"></label>
                                        <select asp-for="CompanyOffice.CompanyId" class="form-control custom-select multisteps-form__input" onchange="onCompanyChange(event)" asp-items="ViewBag.CompanyId"></select>

                                        <span asp-validation-for="CompanyOffice.CompanyId" class="text-danger"></span>
                                    </div>
                                    <div class="col-12 col-sm-6 mt-4 mt-sm-0">
                                        <label asp-for="CompanyOfficeId"></label>
                                        <select asp-for="CompanyOfficeId" class="form-control custom-select multisteps-form__input"></select>

                                        <span asp-validation-for="CompanyOfficeId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="CustomerId"></label>
                                        <select asp-for="CustomerId" class="form-control custom-select multisteps-form__input"></select>
                                        <span asp-validation-for="CustomerId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="TariffId"></label>
                                        <select asp-for="TariffId" class="form-control custom-select multisteps-form__input" onchange="calculateCost()" asp-items="ViewBag.TariffId"></select>
                                        <span asp-validation-for="TariffId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-row mt-4">
                                    <div class="col-12 col-sm-6">
                                        <label asp-for="JobTitle.JobCategoryId"></label>
                                        <select asp-for="JobTitle.JobCategoryId" class="form-control custom-select multisteps-form__input" onchange="onJobCategoryChange(event)" asp-items="ViewBag.JobCategoryId"></select>

                                        <span asp-validation-for="JobTitle.JobCategoryId" class="text-danger"></span>
                                    </div>
                                    <div class="col-12 col-sm-6 mt-4 mt-sm-0">
                                        <label asp-for="JobTitleId"></label>
                                        <select asp-for="JobTitleId" class="form-control custom-select multisteps-form__input"></select>

                                        <span asp-validation-for="JobTitleId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="PositionsCount"></label>
                                        <input asp-for="PositionsCount" class="form-control multisteps-form__input" onchange="calculateCost()" type="number">
                                        <span asp-validation-for="PositionsCount" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="Requirements"></label>
                                        <textarea asp-for="Requirements" class="form-control multisteps-form__input"></textarea>
                                        <span asp-validation-for="Requirements" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-row mt-4">
                                    <div class="col-12">
                                        <label>Estimated cost: <span id="estimatedCost">0</span> @NumberFormatInfo.CurrentInfo.CurrencySymbol</label>
                                    </div>
                                </div>
                                <div class="button-row d-flex mt-4"><button class="btn btn btn-secondary" type="button" onclick="history.back()" title="Back">Back</button><button class="btn btn btn-primary ml-auto" type="submit" title="Create">Create</button></div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        var companyOffices = JSON.parse('@Html.Raw(JsonConvert.SerializeObject(ViewBag.CompanyOffice, new JsonSerializerSettings{StringEscapeHandling = StringEscapeHandling.EscapeHtml}))');
        var customers = JSON.parse('@Html.Raw(JsonConvert.SerializeObject(ViewBag.Customer, new JsonSerializerSettings { StringEscapeHandling = StringEscapeHandling.EscapeHtml }))');
        var jobTitles = JSON.parse('@Html.Raw(JsonConvert.SerializeObject(ViewBag.JobTitle, new JsonSerializerSettings { StringEscapeHandling = StringEscapeHandling.EscapeHtml }))');
        var tariffs = JSON.parse('@Html.Raw(JsonConvert.SerializeObject(ViewBag.Tariff, new JsonSerializerSettings { StringEscapeHandling = StringEscapeHandling.EscapeHtml }))');

        function removeOptions(selectElement) {
            var i, L = selectElement.options.length - 1;
            for (i = L; i >= 0; i--) {
                selectElement.remove(i);
            }
        }

        function onCompanyChange(e) {
            const officeSelect = document.getElementById('@Html.IdFor(model => model.CompanyOfficeId)');
            const customerSelect = document.getElementById('@Html.IdFor(x => x.CustomerId)');

            removeOptions(customerSelect);
            removeOptions(officeSelect);
            companyOffices.filter(x => x.CompanyId == e.target.value).forEach(x => {
                const option = document.createElement('option');
                option.value = x.Value;
                option.text = x.Text;
                officeSelect.add(option);
            });

            customers.filter(x => x.CompanyId == e.target.value).forEach(x => {
                const option = document.createElement('option');
                option.value = x.Value;
                option.text = x.Text;
                customerSelect.add(option);
            });

            customerSelect.disabled = customerSelect.options.length <= 0;
            officeSelect.disabled = officeSelect.options.length <= 0;
        }

        function onJobCategoryChange(e) {
            const jobTitle = document.getElementById('@Html.IdFor(model => model.JobTitleId)');

            removeOptions(jobTitle);
            jobTitles.filter(x => x.JobCategoryId == e.target.value).forEach(x => {
                const option = document.createElement('option');
                option.value = x.Value;
                option.text = x.Text;
                jobTitle.add(option);
            });

            jobTitle.disabled = jobTitle.options.length <= 0;
        }

        function calculateCost() {
            const tariffId = document.getElementById('@Html.IdFor(x => x.TariffId)').value;
            const price = tariffs.filter(x => x.Value == tariffId)[0].Cost;
            const positions = document.getElementById('@Html.IdFor(x => x.PositionsCount)').value;

            document.getElementById("estimatedCost").innerText = (price * positions) || 0;
        }

        $('#@Html.IdFor(x => x.CompanyOffice.CompanyId)').trigger('change');
        $('#@Html.IdFor(x => x.JobTitle.JobCategoryId)').trigger('change');
    </script>
}

RecruitmentAgency/Views/Vacancies/Delete.cshtml
@model RecruitmentAgency.Models.Vacancy

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vacancy</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requirements)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requirements)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PositionsCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PositionsCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyOffice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyOffice.Address)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JobTitle.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Recruiter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Recruiter.FirstName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tariff)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tariff.TariffId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VacancyId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RecruitmentAgency/Views/Vacancies/_DetailsDialog.cshtml
@using RecruitmentAgency.Models
@model RecruitmentAgency.Models.Vacancy

    <div class="modal fade" id="vacancyDetails" role="dialog" tabindex="-1">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Vacancy details</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body">
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.CompanyOffice.Company)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.CompanyOffice.Company.Name)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.CompanyOffice.Address)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.CompanyOffice.Address)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Customer)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Customer.FirstName) @Html.DisplayFor(model => model.Customer.LastName)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Tariff)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Tariff.Name) (Candidate price: @Html.DisplayFor(model => model.Tariff.PriceForCandidate))
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.JobTitle.JobCategory)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.JobTitle.JobCategory.Name)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.JobTitle)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.JobTitle.Name)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.PositionsCount)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.PositionsCount)
                        </dd>
                        <dt class="col-sm-2">
                            Applications
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Applications.Count)
                        </dd>
                        <dt class="col-sm-2">
                            Payments
                        </dt>
                        <dd class="col-sm-10">
                            @(Model.Payments.Sum(x => x.Sum).ToString("C")) of @((Model.PositionsCount * Model.Tariff.PriceForCandidate).ToString("C"))
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.StartDate)
                        </dt>
                        <dd class="col-sm-10">
                            @Model.StartDate.ToString("dd.MM.yyyy")
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.EndDate)
                        </dt>
                        <dd class="col-sm-10">
                            @if (@Model.EndDate.HasValue)
                            {
                                <i class="fas fa-check text-success"></i> @Model.EndDate?.ToString("dd.MM.yyyy")
                            }
                            else
                            {
                                <i class="fa fa-close text-danger" style="color: rgb(251, 2, 2);"></i>
                            }
                        </dd>
                        <dt class="col-12">
                            @Html.DisplayNameFor(model => model.Requirements)
                        </dt>
                        <dd class="col-12">
                            @Html.DisplayFor(model => model.Requirements)
                        </dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    @if (User.IsInRole("Recruiter"))
                    {
                        @if (ViewData["ShowViewApplications"].Equals(true))
                        {
                            <a class="btn btn-primary" asp-controller="Vacancies" asp-action="Applications" asp-route-vacancyId="@Model.VacancyId">View applications</a>
                        }
                        <a class="btn btn-primary" onclick="openApplicationCreate(@Model.VacancyId)">Add application</a>

                        <a class="btn btn-outline-primary" asp-controller="Vacancies" asp-action="Edit" asp-route-id="@Model.VacancyId">Edit</a>
                    }
                    <button class="btn btn-light" type="button" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>