RecruitmentAgency/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace RecruitmentAgency.Models
{
    public partial class Employee
    {
        public Employee()
        {
            SalaryTransactions = new HashSet<SalaryTransaction>();
            Tariffs = new HashSet<Tariff>();
            Vacancies = new HashSet<Vacancy>();
        }

        public int EmployeeId { get; set; }
        [Display(Name = "First name", Prompt = "First name")]
        [Required(ErrorMessage = "First name is required")]
        [RegularExpression("^[A-Z][a-z]+$")]
        public string FirstName { get; set; }
        [Display(Name = "Last name", Prompt = "Last name")]
        [Required(ErrorMessage = "Last name is required")]
        [RegularExpression("^[A-Z][a-z]+$")]
        public string LastName { get; set; }
        [Display(Name = "Department")]
        public int DepartmentId { get; set; }
        [Display(Name = "Role")]
        public int RoleId { get; set; }
        [Display(Name="Rating", Prompt = "Rating")]
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "--")]
        [Range(0, 5, ErrorMessage = "Rating must be in range [0; 5]")]
        public decimal? Rating { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual Department Department { get; set; }
        [Display(Name = "Role")]
        public virtual Role Role { get; set; }
        public virtual PersonalAccount PersonalAccount { get; set; }
        public virtual ICollection<SalaryTransaction> SalaryTransactions { get; set; }
        public virtual ICollection<Tariff> Tariffs { get; set; }
        public virtual ICollection<Vacancy> Vacancies { get; set; }
    }
}

RecruitmentAgency/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecruitmentAgency.Data;
using RecruitmentAgency.Models;
using RecruitmentAgency.ViewModels;

namespace RecruitmentAgency.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly RecruiterAgencyContext _context;

        public EmployeesController(RecruiterAgencyContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 10, string searchQuery = null)
        {
            IQueryable<Employee> recruiterAgencyContext = _context.Employees
                .Include(e => e.Department)
                .ThenInclude(x => x.City)
                .Include(e => e.Role)
                .Include(x => x.PersonalAccount);
            //if (!string.IsNullOrWhiteSpace(searchQuery))
            //{
            //    recruiterAgencyContext = recruiterAgencyContext.Where(x =>
            //        x.FirstName.Contains(searchQuery)
            //        || x.LastName.Contains(searchQuery)
            //        || x.Department.City.Name.Contains(searchQuery)
            //        || x.Department.Address.Contains(searchQuery)
            //        || x.PersonalAccount.Login.Contains(searchQuery)
            //        || x.Role.Name.Contains(searchQuery));
            //}

            //var paginated = await Paginated<Employee>.PaginateAsync(recruiterAgencyContext, pageIndex, pageSize);
            //paginated.SearchQuery = searchQuery;

            return View(await recruiterAgencyContext.ToListAsync());
        }

        // GET: Employees/Recruiters
        [Route("Recruiters")]
        public async Task<IActionResult> Recruiters(int pageIndex = 1, int pageSize = 10, string searchQuery = null)
        {
            IQueryable<Employee> recruiterAgencyContext = _context.Employees
                .Include(e => e.Department)
                .ThenInclude(x => x.City)
                .Include(e => e.Role)
                .Include(x => x.Vacancies)
                .ThenInclude(x => x.Applications)
                .ThenInclude(x => x.ApplicationStatus)
                .Include(x => x.Vacancies)
                .ThenInclude(x => x.Applications)
                .ThenInclude(x => x.Interviews)
                .Where(x => x.Role.Name == "Recruiter");
            //if (!string.IsNullOrWhiteSpace(searchQuery))
            //{
            //    recruiterAgencyContext = recruiterAgencyContext.Where(x =>
            //        x.FirstName.Contains(searchQuery)
            //        || x.LastName.Contains(searchQuery)
            //        || x.Department.City.Name.Contains(searchQuery)
            //        || x.Department.Address.Contains(searchQuery));
            ////}

            //var paginated = await Paginated<Employee>.PaginateAsync(recruiterAgencyContext, pageIndex, pageSize);
            //paginated.SearchQuery = searchQuery;

            return View(await recruiterAgencyContext.ToListAsync());
        }

        // GET: Employees/Recruiters/Details/5
        [Route("Recruiters/Details/{id?}")]
        public async Task<IActionResult> RecruiterDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .ThenInclude(x => x.City)
                .Include(x => x.PersonalAccount)
                .Include(e => e.Role)
                .Where(x => x.Role.Name == "Recruiter")
                .FirstOrDefaultAsync(x => x.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return PartialView("_RecruiterDetailsDialog", employee);
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .ThenInclude(x => x.City)
                .Include(x => x.PersonalAccount)
                .Include(e => e.Role)
                .FirstOrDefaultAsync(x => x.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return PartialView("_DetailsDialog", employee);
        }
        
        // GET: Employees/Recruiters/Create
        [Route("Recruiters/Create")]
        public async Task<IActionResult> CreateRecruiter()
        {
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            return View();
        }

        // GET: Employees/Create
        public async Task<IActionResult> Create()
        {
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "Name");
            return View();
        }
        
        // POST: Employees/Recruiters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("Recruiters/Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRecruiter([Bind("EmployeeId,FirstName,LastName,DepartmentId,PersonalAccount")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.RoleId = await _context.Roles.Where(x => x.Name == "Recruiter").Select(x => x.RoleId).FirstOrDefaultAsync();
                employee.PersonalAccount.CreateDate = employee.CreateDate = DateTime.Now;
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Recruiters));
            }
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            return View(employee);
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,FirstName,LastName,DepartmentId,RoleId,Rating,CreateDate,PersonalAccount,UpdateDate")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.CreateDate = DateTime.Now;
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "Name");
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(x => x.PersonalAccount)
                .FirstOrDefaultAsync(x => x.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            ViewData["RoleId"] = new SelectList(_context.Roles, "RoleId", "Name");
            return View(employee);
        }

        // GET: Employees/Recruiters/Edit/5
        [Route("Recruiters/Edit/{Id?}")]
        public async Task<IActionResult> EditRecruiter(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(x => x.PersonalAccount)
                .Include(x => x.Role)
                .FirstOrDefaultAsync(x => x.EmployeeId == id);
            if (employee == null || employee.Role.Name != "Recruiter")
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = await _context.Departments
                .Include(x => x.City)
                .Select(x => new SelectListItem($"{x.City.Name}, {x.Address}", x.DepartmentId.ToString()))
                .ToListAsync();
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

RecruitmentAgency/Views/Employees/Create.cshtml
@model RecruitmentAgency.Models.Employee

@{
    ViewData["Title"] = "Create employee";
}

<div class="container-fluid">
    <section>
        <div id="multple-step-form-n" class="container overflow-hidden" style="margin-top: 0px;margin-bottom: 10px;padding-bottom: 50px;padding-top: 57px;">

            <div id="multistep-start-row" class="row">
                <div id="multistep-start-column" class="col-12 col-lg-8 m-auto">
                    <form id="main-form" class="multisteps-form__form" asp-action="Create">
                        <div id="single-form-next" class="multisteps-form__panel p-4 shadow rounded bg-white js-active" data-animation="scaleIn">
                            <h3 class="text-center multisteps-form__title">Create employee</h3>
                            <div id="form-content" class="multisteps-form__content">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div id="input-grp-double" class="form-row mt-4">
                                    <div class="col-12 col-sm-6">
                                        <label asp-for="FirstName"></label>
                                        <input asp-for="FirstName" class="form-control multisteps-form__input" type="text">

                                        <span asp-validation-for="FirstName" class="text-danger"></span>
                                    </div>
                                    <div class="col-12 col-sm-6 mt-4 mt-sm-0">
                                        <label asp-for="LastName"></label>
                                        <input asp-for="LastName" class="form-control multisteps-form__input" type="text">

                                        <span asp-validation-for="LastName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="DepartmentId"></label>
                                        <select asp-for="DepartmentId" class="form-control custom-select multisteps-form__input" asp-items="ViewBag.DepartmentId"></select>
                                        <span asp-validation-for="DepartmentId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="RoleId"></label>
                                        <select asp-for="RoleId" class="form-control custom-select multisteps-form__input" asp-items="ViewBag.RoleId"></select>
                                        <span asp-validation-for="RoleId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="PersonalAccount.Login"></label>
                                        <input asp-for="PersonalAccount.Login" class="form-control multisteps-form__input" type="text">
                                        <span asp-validation-for="PersonalAccount.Login" class="text-danger"></span>
                                    </div>
                                </div>
                                <div id="input-grp-single" class="form-row mt-4">
                                    <div class="col-12">
                                        <label asp-for="PersonalAccount.Password"></label>
                                        <input asp-for="PersonalAccount.Password" class="form-control multisteps-form__input" type="password">
                                        <span asp-validation-for="PersonalAccount.Password" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="button-row d-flex mt-4"><button class="btn btn btn-secondary " type="button" onclick="history.back()" title="Back">Back</button><button class="btn btn btn-primary ml-auto " type="submit" title="Create">Create</button></div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RecruitmentAgency/Views/Employees/Delete.cshtml
@model RecruitmentAgency.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.Address)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EmployeeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RecruitmentAgency/Views/Employees/Recruiters.cshtml
@model IEnumerable<RecruitmentAgency.Models.Employee>

@{
    ViewData["Title"] = "Recruiters";
}

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h3 class="text-dark mb-4">Recruiters</h3>
        </div>
        <div class="col text-right">
            <a class="btn btn-primary" asp-controller="Employees" asp-action="CreateRecruiter"><i class="fa fa-plus"></i> Create new</a>
        </div>
    </div>
    <div class="card shadow">
        <div class="card-body">
            @*<form method="get" asp-action="Recruiters">
                <div class="row">
                    <div class="col-md-6 text-nowrap">
                        <div id="dataTable_length" class="dataTables_length" aria-controls="dataTable">
                            <label asp-for="PageSize">
                                Show&nbsp;
                                <select asp-for="PageSize" class="form-control form-control-sm custom-select custom-select-sm" asp-items="Model.DefaultPageSizes" onchange="this.form.submit()">
                                </select>&nbsp;
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="text-md-right dataTables_filter" id="dataTable_filter">
                            <label asp-for="SearchQuery"><input asp-for="SearchQuery" type="search" class="form-control form-control-sm" aria-controls="dataTable" placeholder="Search" /></label>
                        </div>
                    </div>
                </div>
            </form>
            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                @if (Model.TotalItems > 0)
                {*@
            <table class="table my-0" id="dataTable">
                <thead>
                <tr>
                    <th>Full name</th>
                    <th>Department</th>
                    <th>Applications (In work)</th>
                    <th>Scheduled interviews</th>
                    <th>Closed vacancies</th>
                    <th>Rating</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-truncate" title="@($"{item.FirstName} {item.LastName}")">@($"{item.FirstName} {item.LastName}")</td>
                        <td class="text-truncate" title="@($"{item.Department.City.Name}, {item.Department.Address}")">@($"{item.Department.City.Name}, {item.Department.Address}")</td>
                        <td>@item.Vacancies.Select(x => x.Applications.Count(x => x.ApplicationStatus.Name != "Hired")).Sum()</td>
                        <td>@item.Vacancies.SelectMany(x => x.Applications).Select(x => x.Interviews.Count(x => string.IsNullOrWhiteSpace(x.Feedback))).Sum()</td>
                        <td>@item.Vacancies.Count(x => x.EndDate.HasValue)</td>
                        <td>@(item.Rating?.ToString() ?? "--")</td>
                        <td>
                            <div class="dropdown show no-arrow">
                                <button class="btn btn-link btn-sm dropdown-toggle" aria-expanded="false" data-toggle="dropdown" type="button"><i class="fas fa-ellipsis-v text-gray-400"></i></button>
                                <div class="dropdown-menu shadow dropdown-menu-right animated--fade-in">
                                    <a class="dropdown-item" onclick="openRecruiterDetails(@item.EmployeeId)">&nbsp;View details</a>
                                    <a class="dropdown-item" asp-action="EditRecruiter" asp-route-id="@item.EmployeeId">&nbsp;Edit recruiter</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
                </tbody>
                <tfoot>
                <tr>
                    <th><strong>Full name</strong></th>
                    <th><strong>Department</strong></th>
                    <th><strong>Applications (In work)</strong></th>
                    <th><strong>Scheduled interviews</strong></th>
                    <th><strong>Closed vacancies</strong></th>
                    <th><strong>Rating</strong></th>
                    <th></th>
                </tr>
                </tfoot>
            </table>
            @*}
                else
                {
                    <partial name="_NoResultsPlaceholder" />
                }
            </div>
            @if (Model.CountOfPages > 0)
            {
                <partial name="_Pagination" model="Model" />
            }*@
        </div>
    </div>
</div>
    
    @section Scripts {
        <script>
            $('#dataTable').DataTable({
                searchPane: true,
                columnDefs: [
                    {
                        targets: [2, 3, 4, 5],
                        searchPanes: { show: false },
                        searchable: false
                    },
                    {
                        targets: [6],
                        searchPanes: { show: false },
                        searchable: false,
                        orderable: false
                    },
                    {
                        targets: [1],
                        searchPanes: { show: true }
                    }
                ],
                language: {
                    searchPanes: {
                        collapse: { 0: '<i class="fas fa-filter"></i>', _: '<i class="fas fa-filter"></i> (%d)' }
                    }
                },
                buttons: [{
                    extend: 'searchPanes',
                    className: 'btn btn-light',
                    titleAttr: 'Filters'
                }],
                dom:
                    "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6 d-flex flex-row-reverse no-gutters align-items-center'" +
                        "<'col-sm-auto col-12 text-right ml-2 mb-2'B><'col-sm-auto col-12'f>>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>"
            });
        </script>
    }

RecruitmentAgency/Views/Employees/_DetailsDialog.cshtml
@model RecruitmentAgency.Models.Employee

<div class="modal fade" id="employeeDetails" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Employee details</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <dl class="row">
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Department.City)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Department.City.Name)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Department.Address)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Department.Address)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Role)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Role.Name)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.PersonalAccount.Login)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.PersonalAccount.Login)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Rating)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Rating)
                    </dd>
                </dl>
            </div>
            <div class="modal-footer">
                <a class="btn btn-outline-primary" asp-controller="Employees" asp-action="Edit" asp-route-id="@Model.EmployeeId">Edit</a>
                <button class="btn btn-light" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

RecruitmentAgency/Views/Employees/_RecruiterDetailsDialog.cshtml
@model RecruitmentAgency.Models.Employee

<div class="modal fade" id="recruiterDetails" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Recruiter details</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <dl class="row">
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Department.City)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Department.City.Name)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Department.Address)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Department.Address)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.PersonalAccount.Login)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.PersonalAccount.Login)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Rating)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Rating)
                    </dd>
                </dl>
            </div>
            <div class="modal-footer">
                <a class="btn btn-outline-primary" asp-controller="Employees" asp-action="EditRecruiter" asp-route-id="@Model.EmployeeId">Edit</a>
                <button class="btn btn-light" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>